import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import type { Analysis, Dashboard, DebtAnalysis, HouseholdRole, NetWorth, NotificationPage, Portfolio } from '../../api/contracts';
import { localYearMonth } from '../../shared/runtime';
import { DataPanel, PageScaffold, QueryState, StatusTag, dateText, money, type RequestFn } from '../common';

export function DashboardPage({ request, role, displayName }: { request: RequestFn; role: HouseholdRole; displayName: string }) {
  const [month, setMonth] = useState(localYearMonth());
  const dashboard = useQuery({ queryKey: ['dashboard', month], queryFn: () => request<Dashboard>(`/api/dashboard?month=${month}&rollupCategories=true`) });
  const netWorth = useQuery({ queryKey: ['net-worth'], queryFn: () => request<NetWorth>('/api/net-worth') });
  const debt = useQuery({ queryKey: ['debt-analysis'], queryFn: () => request<DebtAnalysis>('/api/debt-analysis') });
  const portfolio = useQuery({ queryKey: ['portfolio'], queryFn: () => request<Portfolio>('/api/portfolio') });
  const notifications = useQuery({ queryKey: ['notifications'], queryFn: () => request<NotificationPage>('/api/notifications') });
  const analysis = useQuery({ queryKey: ['analysis', month], queryFn: () => request<Analysis>(`/api/analysis?month=${month}&rollupCategories=true`) });
  const greeting = new Date().getHours() < 12 ? '早上好' : new Date().getHours() < 18 ? '下午好' : '晚上好';
  return <PageScaffold eyebrow={`${greeting}，${displayName}`} title="家庭总览" description="把现金流、净资产、预算、投资和负债放在同一张家庭账页。">
    <div className="dashboard-toolbar"><label>查看月份<input type="month" value={month} onChange={e => setMonth(e.target.value)} /></label><span className="server-source">所有金额来自服务器权威汇总</span></div>
    <div className="metric-grid">
      <Metric label="家庭净资产" value={money(netWorth.data?.netWorth)} note={`资产 ${money(netWorth.data?.asset)} · 负债 ${money(netWorth.data?.liability)}`} loading={netWorth.isLoading} error={netWorth.error} />
      <Metric label="本月结余" value={money(dashboard.data?.summary.balance)} note={`收入 ${money(dashboard.data?.summary.income)} · 支出 ${money(dashboard.data?.summary.expense)}`} loading={dashboard.isLoading} error={dashboard.error} tone={Number(dashboard.data?.summary.balance) < 0 ? 'negative' : 'positive'} />
      <Metric label="家庭负债率" value={debt.data ? `${debt.data.debtRatioPercent}%` : '—'} note={`${debt.data?.loans.length ?? '—'} 笔活跃贷款`} loading={debt.isLoading} error={debt.error} />
      <Metric label="投资累计收益" value={money(portfolio.data?.totals.totalProfit)} note={`市值 ${money(portfolio.data?.totals.marketValue)} · ${portfolio.data?.totals.unpricedPositions ?? '—'} 个缺价`} loading={portfolio.isLoading} error={portfolio.error} tone={Number(portfolio.data?.totals.totalProfit) < 0 ? 'negative' : 'positive'} />
    </div>
    <div className="dashboard-grid">
      <DataPanel title="本月现金流" meta="每日收入与支出 · 服务器汇总" className="wide-panel"><QueryState loading={dashboard.isLoading} error={dashboard.error} empty={!dashboard.data?.daily.length} emptyTitle="本月还没有现金流"><CashflowChart data={dashboard.data?.daily ?? []} /></QueryState></DataPanel>
      <DataPanel title="资产配置" meta="按服务器净资产口径"><QueryState loading={netWorth.isLoading} error={netWorth.error} empty={!netWorth.data?.allocation.length} emptyTitle="暂无资产配置"><div className="allocation-list">{netWorth.data?.allocation.map((item, index) => <div key={item.type}><span className={`allocation-dot tone-${index % 5}`} /><strong>{allocationLabel(item.type)}</strong><span>{money(item.amount)}</span><b>{item.sharePercent}%</b></div>)}</div></QueryState></DataPanel>
      <DataPanel title="预算执行" meta={netWorth.data?.budget.activeBudgetCount ? `${netWorth.data.budget.activeBudgetCount} 项活跃预算` : '当前状态'}><QueryState loading={netWorth.isLoading} error={netWorth.error}><div className="budget-summary"><div><span>计划</span><strong>{money(netWorth.data?.budget.planned)}</strong></div><div><span>已用</span><strong>{money(netWorth.data?.budget.spent)}</strong></div><footer>{netWorth.data?.budget.overLimitCount ? <StatusTag tone="danger">{netWorth.data.budget.overLimitCount} 项超支</StatusTag> : netWorth.data?.budget.nearLimitCount ? <StatusTag tone="warning">{netWorth.data.budget.nearLimitCount} 项接近额度</StatusTag> : <StatusTag tone="success">预算状态正常</StatusTag>}<a href="/workspace/budgets">查看预算</a></footer></div></QueryState></DataPanel>
      <DataPanel title="近期提醒" meta={notifications.data ? `${notifications.data.unreadCount} 条未读` : '读取中'} action={<a href="/workspace/notifications">查看全部</a>}><QueryState loading={notifications.isLoading} error={notifications.error} empty={!notifications.data?.items.length} emptyTitle="暂无提醒"><div className="dashboard-reminders"><strong>{notifications.data?.unreadCount ?? 0} 条未读</strong>{notifications.data?.items.slice(0,3).map(item => <a href="/workspace/notifications" key={item.id}><i /><span><b>{item.title}</b><small>{dateText(item.dueAt)}</small></span></a>)}</div></QueryState></DataPanel>
      <DataPanel title="行情与持仓" meta="来源、新鲜度和缺价状态"><QueryState loading={netWorth.isLoading} error={netWorth.error}><div className="market-summary"><strong>{money(netWorth.data?.investment.marketValue)}</strong><p>{netWorth.data?.investment.positionCount ?? '—'} 个持仓 · {netWorth.data?.investment.unpricedPositionCount ?? '—'} 个缺价</p><div>{netWorth.data?.investment.stalePrice && <StatusTag tone="warning">行情已过期</StatusTag>}{netWorth.data?.investment.missingPrice && <StatusTag tone="danger">存在缺失价格</StatusTag>}{netWorth.data?.investment.manualPrice && <StatusTag tone="blue">含手工价格</StatusTag>}{!netWorth.data?.investment.stalePrice && !netWorth.data?.investment.missingPrice && <StatusTag tone="success">行情状态正常</StatusTag>}</div><a href="/workspace/investments">查看投资</a></div></QueryState></DataPanel>
      <DataPanel title="家庭洞察" meta={`分析历史：${analysis.data?.historyStatus ?? '读取中'}`} className="wide-panel"><QueryState loading={analysis.isLoading} error={analysis.error} empty={!analysis.data?.insights.length} emptyTitle="数据仍在积累" emptyDetail="有足够历史后，服务器会在这里生成规则洞察。"><div className="insight-grid">{analysis.data?.insights.map((item, index) => <article key={`${item.type}-${index}`}><span>{item.type}</span><h3>{item.title}</h3><p>{item.message}</p><strong>{item.metric}</strong></article>)}</div></QueryState></DataPanel>
    </div>
    <section className="analysis-section"><header><div><p className="section-kicker">趋势与进度</p><h2>综合分析</h2></div><span>只展示服务器返回值</span></header><div className="analysis-grid"><DataPanel title="净资产历史"><QueryState loading={netWorth.isLoading} error={netWorth.error} empty={!netWorth.data?.history.length} emptyTitle="还没有历史快照"><div className="history-bars">{netWorth.data?.history.slice(-8).map(item => <div key={item.snapshotOn}><span>{dateText(item.snapshotOn).slice(5)}</span><i title={money(item.netWorth)} style={{ '--bar-size': `${Math.max(8, Math.min(100, Math.abs(Number(item.netWorth)) / Math.max(...netWorth.data.history.map(point => Math.abs(Number(point.netWorth))), 1) * 100))}%` } as React.CSSProperties} /><strong>{money(item.netWorth)}</strong></div>)}</div></QueryState></DataPanel><DataPanel title="贷款进度"><QueryState loading={debt.isLoading} error={debt.error} empty={!debt.data?.loans.length} emptyTitle="没有活跃贷款"><div className="debt-list">{debt.data?.loans.map(item => <div key={item.loanId}><header><strong>{item.loanName}</strong><span>已还 {item.repaidPercent}%</span></header><div className="progress-track"><i style={{ width: `${item.repaidPercent}%` }} /></div><p>剩余 {money(item.currentPrincipal)} / 原始 {money(item.originalPrincipal)}</p></div>)}</div></QueryState></DataPanel><DataPanel title="成员支出"><QueryState loading={dashboard.isLoading} error={dashboard.error} empty={!dashboard.data?.expenseByMember.length} emptyTitle="暂无成员支出"><div className="member-spend-list">{dashboard.data?.expenseByMember.map(item => <div key={item.memberId}><span>{item.memberName}</span><strong>{money(item.amount)}</strong></div>)}</div></QueryState></DataPanel></div></section>
    {role === 'MEMBER' && <div className="source-note">家庭成员可查看共同财务；管理类操作由所有者或管理员完成。</div>}
  </PageScaffold>;
}

function Metric({ label, value, note, loading, error, tone }: { label: string; value: string; note: string; loading: boolean; error: unknown; tone?: string }) {
  return <article className="metric-card"><span>{label}</span>{loading ? <b className="skeleton-line">读取中</b> : error ? <b className="metric-error">暂不可用</b> : <b className={tone}>{value}</b>}<small>{error ? '该模块读取失败，其他数据仍可使用' : note}</small></article>;
}

function CashflowChart({ data }: { data: Dashboard['daily'] }) {
  const max = Math.max(1, ...data.flatMap(item => [Number(item.income), Number(item.expense)]));
  return <div className="cashflow-chart" role="img" aria-label="每日收入与支出柱状图">{data.map(item => <div className="chart-day" key={item.date}><div><i className="income-bar" style={{ height: `${Math.max(2, Number(item.income) / max * 100)}%` }} title={`收入 ${money(item.income)}`} /><i className="expense-bar" style={{ height: `${Math.max(2, Number(item.expense) / max * 100)}%` }} title={`支出 ${money(item.expense)}`} /></div><span>{item.date.slice(8)}</span></div>)}</div>;
}

function allocationLabel(value: string) { return ({ ACCOUNT: '现金账户', PROPERTY: '房产', VEHICLE: '车辆', OTHER: '其他资产', INVESTMENT: '投资' } as Record<string,string>)[value] ?? value; }
