import { useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import Button from '@douyinfe/semi-ui/lib/es/button';
import type { CreatedInvite, Family, FamilyInvite, HouseholdRole, Membership } from '../../api/contracts';
import { ConfirmDialog, DataPanel, Drawer, FormError, PageScaffold, QueryState, StatusTag, dateText, isManager, type RequestFn } from '../common';

export function FamilyPage({ request, role, householdName }: { request: RequestFn; role: HouseholdRole; householdName?: string }) {
  const client = useQueryClient();
  const family = useQuery({ queryKey: ['family'], queryFn: () => request<Family>('/api/family') });
  const memberships = useQuery({ queryKey: ['memberships'], queryFn: () => request<{ items: Membership[] }>('/api/family/memberships?page=0&size=50') });
  const invites = useQuery({ queryKey: ['family-invites'], queryFn: () => request<{ items: FamilyInvite[] }>('/api/family/invites?page=0&size=50'), enabled: isManager(role) });
  const [inviteOpen, setInviteOpen] = useState(false);
  const [inviteRole, setInviteRole] = useState<'MEMBER' | 'ADMIN'>('MEMBER');
  const [maxUses, setMaxUses] = useState('5');
  const [createdInvite, setCreatedInvite] = useState<CreatedInvite | null>(null);
  const [transferId, setTransferId] = useState<number | null>(null);
  const [archiveOpen, setArchiveOpen] = useState(false);
  const [confirmName, setConfirmName] = useState('');
  const [rename, setRename] = useState<string | null>(null);
  const [password, setPassword] = useState<{ currentPassword: string; newPassword: string } | null>(null);
  const invalidate = () => Promise.all([client.invalidateQueries({ queryKey: ['family'] }), client.invalidateQueries({ queryKey: ['memberships'] }), client.invalidateQueries({ queryKey: ['family-invites'] })]);
  const createInvite = useMutation({ mutationFn: () => request<CreatedInvite>('/api/family/invites', { method: 'POST', body: { role: inviteRole, maxUses: Number(maxUses) } }), onSuccess: async value => { setCreatedInvite(value); await client.invalidateQueries({ queryKey: ['family-invites'] }); } });
  const revoke = useMutation({ mutationFn: (id: number) => request<void>(`/api/family/invites/${id}`, { method: 'DELETE' }), onSuccess: () => client.invalidateQueries({ queryKey: ['family-invites'] }) });
  const changeRole = useMutation({ mutationFn: ({ id, nextRole }: { id: number; nextRole: 'ADMIN' | 'MEMBER' }) => request<Membership>(`/api/family/memberships/${id}`, { method: 'PATCH', body: { role: nextRole } }), onSuccess: invalidate });
  const transfer = useMutation({ mutationFn: (membershipId: number) => request<void>('/api/family/transfer-ownership', { method: 'POST', body: { membershipId } }), onSuccess: async () => { setTransferId(null); await invalidate(); } });
  const saveRename = useMutation({ mutationFn: (name: string) => request<Family>('/api/family', { method: 'PATCH', body: { name } }), onSuccess: async () => { setRename(null); await client.invalidateQueries({ queryKey: ['family'] }); } });
  const changePassword = useMutation({ mutationFn: (value: NonNullable<typeof password>) => request<void>('/api/auth/change-password', { method: 'POST', body: value }), onSuccess: () => setPassword(null) });
  const archive = useMutation({ mutationFn: () => request<void>('/api/family', { method: 'DELETE', body: { confirmName } }), onSuccess: () => window.location.assign('/login') });
  const currentName = family.data?.name ?? householdName ?? '';
  const manager = isManager(role);
  return <PageScaffold title="家庭与成员" description="管理家庭资料、协作身份与一次性邀请。" primaryAction={manager ? { label: '邀请成员', onClick: () => { setInviteOpen(true); setCreatedInvite(null); } } : undefined}>
    <div className="family-banner"><span className="family-seal">家</span><div><p>当前家庭</p><h2>{currentName || '读取中'}</h2><span>{memberships.data?.items.length ?? '—'} 位协作者 · 你的身份：{role === 'OWNER' ? '所有者' : role === 'ADMIN' ? '管理员' : '成员'}</span></div>{role === 'OWNER' && <Button size="small" onClick={() => setRename(currentName)}>修改名称</Button>}</div>
    <div className="two-column-layout family-layout"><DataPanel title="家庭成员" meta="角色决定可执行的财务操作"><QueryState loading={memberships.isLoading} error={memberships.error} empty={!memberships.data?.items.length}><div className="member-list">{memberships.data?.items.map(item => <article key={item.id}><span className="user-avatar">{item.displayName.slice(0,1)}</span><div><h3>{item.displayName}</h3><p>{item.email}</p></div><StatusTag tone={item.role === 'OWNER' ? 'blue' : item.role === 'ADMIN' ? 'success' : 'neutral'}>{item.role === 'OWNER' ? '所有者' : item.role === 'ADMIN' ? '管理员' : '成员'}</StatusTag>{role === 'OWNER' && item.role !== 'OWNER' && <div className="card-actions"><button onClick={() => changeRole.mutate({ id: item.id, nextRole: item.role === 'ADMIN' ? 'MEMBER' : 'ADMIN' })}>{item.role === 'ADMIN' ? '设为成员' : '设为管理员'}</button><button onClick={() => setTransferId(item.id)}>转让所有权</button></div>}</article>)}</div></QueryState></DataPanel>
      <div className="stacked-panels">{manager && <DataPanel title="邀请记录" meta="邀请原文只在创建成功时展示一次"><QueryState loading={invites.isLoading} error={invites.error} empty={!invites.data?.items.length} emptyTitle="还没有邀请"><div className="invite-list">{invites.data?.items.map(item => <article key={item.id}><div><strong>{item.role === 'ADMIN' ? '管理员邀请' : '成员邀请'}</strong><p>已用 {item.usedCount}/{item.maxUses} · 到期 {dateText(item.expiresAt)}</p></div>{item.revokedAt ? <StatusTag>已撤销</StatusTag> : <button onClick={() => revoke.mutate(item.id)}>撤销</button>}</article>)}</div></QueryState></DataPanel>}<DataPanel title="账号与安全"><div className="settings-actions"><button aria-label="修改登录密码" onClick={() => setPassword({ currentPassword: '', newPassword: '' })}><strong>修改登录密码</strong><span>更新后继续使用当前会话</span></button>{role === 'OWNER' && <button aria-label="归档家庭" className="danger-zone" onClick={() => setArchiveOpen(true)}><strong>归档家庭</strong><span>停止成员登录，保留历史财务数据</span></button>}</div></DataPanel></div></div>
    <Drawer open={inviteOpen} title="邀请成员" description="邀请码只在本次成功页面显示，请通过可信方式发送。" onClose={() => { setInviteOpen(false); setCreatedInvite(null); }}>{createdInvite ? <div className="invite-success"><StatusTag tone="success">邀请已创建</StatusTag><label>一次性邀请码<input readOnly value={createdInvite.token} /></label><Button theme="solid" type="primary" onClick={() => navigator.clipboard.writeText(createdInvite.token)}>复制邀请码</Button><p>{createdInvite.role === 'ADMIN' ? '管理员' : '成员'} · 最多 {createdInvite.maxUses} 次 · {dateText(createdInvite.expiresAt)} 到期</p></div> : <form className="feature-form" onSubmit={e => { e.preventDefault(); createInvite.mutate(); }}><FormError error={createInvite.error} /><label>邀请角色<select value={inviteRole} onChange={e => setInviteRole(e.target.value as 'MEMBER' | 'ADMIN')}><option value="MEMBER">家庭成员</option>{role === 'OWNER' && <option value="ADMIN">家庭管理员</option>}</select></label><label>最多使用次数<input type="number" min="1" max="100" value={maxUses} onChange={e => setMaxUses(e.target.value)} /></label><Button htmlType="submit" theme="solid" type="primary" loading={createInvite.isPending}>创建邀请</Button></form>}</Drawer>
    <Drawer open={rename !== null} title="修改家庭名称" onClose={() => setRename(null)}>{rename !== null && <form className="feature-form" onSubmit={e => { e.preventDefault(); saveRename.mutate(rename); }}><FormError error={saveRename.error} /><label>家庭名称<input required value={rename} onChange={e => setRename(e.target.value)} /></label><Button htmlType="submit" theme="solid" type="primary">保存名称</Button></form>}</Drawer>
    <Drawer open={password !== null} title="修改登录密码" onClose={() => setPassword(null)}>{password && <form className="feature-form" onSubmit={(e: FormEvent) => { e.preventDefault(); changePassword.mutate(password); }}><FormError error={changePassword.error} /><label>当前密码<input type="password" required value={password.currentPassword} onChange={e => setPassword({ ...password, currentPassword: e.target.value })} /></label><label>新密码<input type="password" minLength={8} maxLength={72} required value={password.newPassword} onChange={e => setPassword({ ...password, newPassword: e.target.value })} /></label><Button htmlType="submit" theme="solid" type="primary">更新密码</Button></form>}</Drawer>
    <ConfirmDialog open={transferId !== null} title="转让家庭所有权？" detail="转让后，你会继承对方原有角色；只有新所有者可以再次转让或归档家庭。" confirmLabel="确认转让" onClose={() => setTransferId(null)} onConfirm={() => transferId !== null && transfer.mutate(transferId)} />
    {archiveOpen && <div className="sheet-backdrop dialog-backdrop"><section className="confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="archive-title"><h2 id="archive-title">归档家庭</h2><p>成员将无法继续登录，但历史财务数据与备份不会被物理删除。</p><FormError error={archive.error} /><label>输入“{currentName}”确认<input value={confirmName} onChange={e => setConfirmName(e.target.value)} /></label><footer><Button onClick={() => setArchiveOpen(false)}>取消</Button><Button theme="solid" type="danger" disabled={confirmName !== currentName} loading={archive.isPending} onClick={() => archive.mutate()}>归档家庭</Button></footer></section></div>}
  </PageScaffold>;
}
