import {InvestmentButton,InvestmentActions} from './investment-ui';
import {Fragment,useState,type ReactNode} from 'react';
import {Search,ChevronDown} from 'lucide-react';
import type {PortfolioPosition} from '../../api/contracts';
import {money} from '../common';
import {formatUnitPrice} from '../../shared/currency';

type Props={onRefresh?:()=>void;refreshing?:boolean;positions:PortfolioPosition[];manager:boolean;verifiedIds:Set<number>;onView:(p:PortfolioPosition)=>void;onBuy:(p:PortfolioPosition)=>void;onSell:(p:PortfolioPosition)=>void;priceState:(p:PortfolioPosition,detail?:boolean)=>ReactNode};
export function HoldingsDashboard({positions,manager,verifiedIds,onView,onBuy,onSell,priceState,onRefresh,refreshing=false}:Props){
 const [search,setSearch]=useState(''),[market,setMarket]=useState('ALL'),[account,setAccount]=useState('ALL'),[hideClosed,setHideClosed]=useState(true),[expanded,setExpanded]=useState<string|null>(null);
 const accounts=[...new Map(positions.map(p=>[p.accountId,p.accountName])).entries()];
 const filtered=positions.filter(p=>(!hideClosed||Number(p.quantity)>0)&&(account==='ALL'||String(p.accountId)===account)&&(market==='ALL'||(market==='CN'?!['US','HK'].includes(p.market??''):p.market===market))&&`${p.name} ${p.tsCode} ${p.symbol??''}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()));
 return <section className="holdings-dashboard" aria-label="我的持仓"><div className="holdings-toolbar"><label className="holdings-search"><Search size={17}/><input type="search" aria-label="搜索持仓" placeholder="搜索证券或代码" value={search} onChange={e=>setSearch(e.target.value)}/></label><label><span className="sr-only">市场筛选</span><select aria-label="市场筛选" value={market} onChange={e=>setMarket(e.target.value)}><option value="ALL">全部市场</option><option value="CN">A 股</option><option value="HK">港股</option><option value="US">美股</option></select></label><label><span className="sr-only">账户筛选</span><select aria-label="账户筛选" value={account} onChange={e=>setAccount(e.target.value)}><option value="ALL">全部账户</option>{accounts.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label className="hide-closed"><input type="checkbox" checked={hideClosed} onChange={e=>setHideClosed(e.target.checked)}/>隐藏已清仓</label>{onRefresh&&<InvestmentButton variant="quiet" size="small" disabled={refreshing} onClick={onRefresh}>{refreshing?'更新中…':'刷新报价'}</InvestmentButton>}</div>
  <table className="holdings-table"><thead><tr><th>证券 / 账户</th><th>参考单价</th><th>持仓市值（原币）</th><th>累计收益（原币）</th><th>操作</th></tr></thead><tbody>{filtered.map(p=>{const key=`${p.accountId}-${p.securityId}`,currency=p.currency??'CNY';return <Fragment key={key}><tr>
   <td data-label="证券"><div className="holding-identity"><span className="holding-mark" aria-hidden="true">{/^[0-9]/.test(p.symbol??p.tsCode)?p.name.slice(0,1):(p.symbol??p.tsCode).slice(0,2)}</span><div><button className="stock-link" onClick={()=>onView(p)}>{p.name}</button><small>{p.tsCode} · {p.accountName}</small></div></div></td>
   <td data-label="参考单价"><strong>{formatUnitPrice(p.price,currency)}</strong>{p.averageCost!=null&&Number(p.quantity)>0&&<small>持仓均价 {formatUnitPrice(p.averageCost,currency)}</small>}{p.price==null&&<small>暂无报价</small>}</td><td data-label="持仓市值"><strong>{money(p.marketValue,currency)}</strong>{p.base&&currency!=='CNY'&&<small>折合人民币 {money(p.base.marketValue)}</small>}{p.valuationStatus==='COST_ESTIMATE'&&<small>缺价 · 成本估算 {money(p.estimatedValue,currency)}</small>}</td>
   <td data-label="累计收益" className={p.totalProfit==null?'':Number(p.totalProfit)>=0?'positive':'negative'}><strong>{money(p.totalProfit,currency)}</strong></td>
   <td className="holding-actions">{manager&&<InvestmentActions label={`${p.name}更多操作`} actions={[...(verifiedIds.has(p.securityId)||p.market==='US'||p.market==='HK'?[{label:`记录买入${p.name}`,onClick:()=>onBuy(p)}]:[]),...(Number(p.quantity)>0?[{label:`记录卖出${p.name}`,onClick:()=>onSell(p)}]:[])]}/>}<InvestmentButton variant="quiet" size="small" aria-expanded={expanded===key} aria-label={`${p.name}持仓明细`} onClick={()=>setExpanded(expanded===key?null:key)}>明细<ChevronDown size={14}/></InvestmentButton></td>
  </tr>{expanded===key&&<tr className="holding-detail-row"><td colSpan={5}><dl><div><dt>持有数量</dt><dd>{p.quantity} 股</dd></div><div><dt>持仓成本</dt><dd>{money(p.cost,currency)}</dd></div><div><dt>参考价格</dt><dd>{formatUnitPrice(p.price,currency)}</dd></div><div><dt>报价来源与时间</dt><dd>{priceState(p,true)}</dd></div><div><dt>已实现收益</dt><dd>{money(p.realizedProfit,currency)}</dd></div>{p.base&&<><div><dt>人民币成本</dt><dd>{money(p.base.cost)}</dd></div><div><dt>人民币累计收益</dt><dd className={p.base.totalProfit==null?'':Number(p.base.totalProfit)>=0?'positive':'negative'}>{money(p.base.totalProfit)}</dd></div><div><dt>折算汇率日期</dt><dd>{p.base.fxDate??'待补充'}</dd></div></>}</dl><button onClick={()=>onView(p)}>查看行情</button></td></tr>}</Fragment>;})}</tbody></table>
  {!filtered.length&&<div className="holdings-empty">没有符合筛选条件的持仓。<button onClick={()=>{setSearch('');setMarket('ALL');setAccount('ALL');setHideClosed(false);}}>清除筛选</button></div>}
 </section>;
}
