import { useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import Button from '@douyinfe/semi-ui/lib/es/button';
import type { HouseholdRole, InvestmentAccount, InvestmentTrade, InvestmentTradeType, MarketPrice, Portfolio, Security } from '../../api/contracts';
import { ConfirmDialog, DataPanel, Drawer, FormError, PageScaffold, QueryState, StatusTag, dateText, isManager, money, type RequestFn } from '../common';

type TradeDraft = { id?: number; accountId: string; securityId: string; type: InvestmentTradeType; quantity: string; price: string; fee: string; tradedOn: string };

export function InvestmentsPage({ request, role }: { request: RequestFn; role: HouseholdRole }) {
  const client = useQueryClient();
  const [tab, setTab] = useState<'positions' | 'trades' | 'accounts' | 'quotes'>('positions');
  const [trade, setTrade] = useState<TradeDraft | null>(null);
  const [securityQuery, setSecurityQuery] = useState('');
  const [accountDraft, setAccountDraft] = useState<{ id?: number; name: string; brokerName: string; currency: string } | null>(null);
  const [manualQuote, setManualQuote] = useState<MarketPrice | null>(null);
  const [manual, setManual] = useState({ price: '', effectiveOn: new Date().toISOString().slice(0, 10), note: '' });
  const [deleteTrade, setDeleteTrade] = useState<number | null>(null);
  const portfolio = useQuery({ queryKey: ['portfolio'], queryFn: () => request<Portfolio>('/api/portfolio') });
  const accounts = useQuery({ queryKey: ['investment-accounts'], queryFn: () => request<{ items: InvestmentAccount[] }>('/api/investment-accounts?status=ACTIVE&page=0&size=50') });
  const trades = useQuery({ queryKey: ['investment-trades'], queryFn: () => request<{ items: InvestmentTrade[] }>('/api/investment-trades?page=0&size=50') });
  const quotes = useQuery({ queryKey: ['market-quotes'], queryFn: () => request<MarketPrice[]>('/api/market-quotes') });
  const securities = useQuery({ queryKey: ['securities', securityQuery], queryFn: () => request<{ items: Security[] }>(`/api/securities/search?q=${encodeURIComponent(securityQuery)}&page=0&size=20`), enabled: trade !== null });
  const manager = isManager(role);
  const invalidateInvestment = async () => Promise.all(['portfolio','investment-trades','market-quotes','net-worth'].map(key => client.invalidateQueries({ queryKey: [key] })));
  const saveTrade = useMutation({ mutationFn: (value: TradeDraft) => request(value.id ? `/api/investment-trades/${value.id}` : '/api/investment-trades', { method: value.id ? 'PATCH' : 'POST', body: { accountId: Number(value.accountId), securityId: Number(value.securityId), type: value.type, quantity: value.type === 'BUY' || value.type === 'SELL' ? value.quantity : null, price: value.price, fee: value.type === 'BUY' || value.type === 'SELL' ? value.fee || '0' : null, tradedOn: value.tradedOn, sourceType: 'MANUAL', sourceId: null } }), onSuccess: async () => { setTrade(null); await invalidateInvestment(); } });
  const removeTrade = useMutation({ mutationFn: (id: number) => request<void>(`/api/investment-trades/${id}`, { method: 'DELETE' }), onSuccess: async () => { setDeleteTrade(null); await invalidateInvestment(); } });
  const saveAccount = useMutation({ mutationFn: (value: NonNullable<typeof accountDraft>) => request<InvestmentAccount>(value.id ? `/api/investment-accounts/${value.id}` : '/api/investment-accounts', { method: value.id ? 'PATCH' : 'POST', body: value }), onSuccess: async () => { setAccountDraft(null); await client.invalidateQueries({ queryKey: ['investment-accounts'] }); } });
  const archiveAccount = useMutation({ mutationFn: (id: number) => request<void>(`/api/investment-accounts/${id}`, { method: 'DELETE' }), onSuccess: () => client.invalidateQueries({ queryKey: ['investment-accounts'] }) });
  const refresh = useMutation({ mutationFn: () => request<{ state: string; refreshed: number; error: string | null; quotes: MarketPrice[] }>('/api/market-quotes/refresh', { method: 'POST' }), onSuccess: async () => { await Promise.all([client.invalidateQueries({ queryKey: ['market-quotes'] }), client.invalidateQueries({ queryKey: ['portfolio'] }), client.invalidateQueries({ queryKey: ['net-worth'] })]); } });
  const setManualPrice = useMutation({ mutationFn: () => request<MarketPrice>(`/api/securities/${manualQuote!.securityId}/manual-price`, { method: 'POST', body: manual }), onSuccess: async () => { setManualQuote(null); await invalidateInvestment(); } });
  const blankTrade = (): TradeDraft => ({ accountId: '', securityId: '', type: 'BUY', quantity: '', price: '', fee: '0', tradedOn: new Date().toISOString().slice(0, 10) });
  const edit = (item: InvestmentTrade): TradeDraft => ({ id: item.id, accountId: String(item.accountId), securityId: String(item.security.id), type: item.type, quantity: item.quantity ? String(item.quantity) : '', price: item.price, fee: item.fee, tradedOn: item.tradedOn });
  const tradeLabel = (value: InvestmentTradeType) => ({ BUY: '买入', SELL: '卖出', DIVIDEND: '分红', FEE: '费用' }[value]);
  return <PageScaffold title="投资持仓" description="持仓、成本与收益由交易历史和服务器行情推导。" primaryAction={manager ? { label: '记一笔投资', onClick: () => setTrade(blankTrade()) } : undefined} readonly={!manager}>
    <div className="summary-strip"><div><span>组合市值</span><strong>{money(portfolio.data?.totals.marketValue)}</strong><small>服务器持仓汇总</small></div><div><span>累计收益</span><strong className={Number(portfolio.data?.totals.totalProfit) >= 0 ? 'positive' : 'negative'}>{money(portfolio.data?.totals.totalProfit)}</strong><small>已实现 + 浮动</small></div><div><span>缺少价格</span><strong>{portfolio.data?.totals.unpricedPositions ?? '—'} 个</strong><small>不会猜测未知市值</small></div></div>
    <nav className="segmented-tabs" aria-label="投资模块">{([['positions','持仓'],['trades','交易'],['accounts','账户'],['quotes','行情']] as const).map(([value,label]) => <button key={value} className={tab === value ? 'active' : ''} onClick={() => setTab(value)}>{label}</button>)}</nav>
    {tab === 'positions' && <QueryState loading={portfolio.isLoading} error={portfolio.error} empty={!portfolio.data?.positions.length} emptyTitle="还没有投资持仓" emptyDetail={manager ? '先创建投资账户，再记录一笔买入。' : '家庭管理员还没有录入投资。'}><div className="responsive-data"><table><thead><tr><th>证券</th><th>账户</th><th>数量</th><th>成本</th><th>价格</th><th>市值</th><th>总收益</th><th>来源</th></tr></thead><tbody>{portfolio.data?.positions.map(item => <tr key={`${item.accountId}-${item.securityId}`}><td><strong>{item.name}</strong><small>{item.tsCode}</small></td><td>{item.accountName}<small>{item.brokerName}</small></td><td>{item.quantity}</td><td>{money(item.cost)}</td><td>{money(item.price)}</td><td>{money(item.marketValue)}</td><td className={Number(item.totalProfit) >= 0 ? 'positive' : 'negative'}>{money(item.totalProfit)}</td><td><PriceState source={item.source} stale={item.stale} tradeDate={item.tradeDate} error={item.error} /></td></tr>)}</tbody></table><div className="mobile-card-list">{portfolio.data?.positions.map(item => <article className="record-card" key={`${item.accountId}-${item.securityId}`}><header><div><strong>{item.name}</strong><small>{item.tsCode}</small></div><b>{money(item.marketValue)}</b></header><p>{item.quantity} 股 · 成本 {money(item.cost)}</p><footer><PriceState source={item.source} stale={item.stale} tradeDate={item.tradeDate} error={item.error} /><strong className={Number(item.totalProfit) >= 0 ? 'positive' : 'negative'}>{money(item.totalProfit)}</strong></footer></article>)}</div></div></QueryState>}
    {tab === 'trades' && <DataPanel title="交易记录" meta="买入、卖出、分红和费用"><QueryState loading={trades.isLoading} error={trades.error} empty={!trades.data?.items.length} emptyTitle="还没有交易"><div className="responsive-data"><table><thead><tr><th>日期</th><th>证券</th><th>类型</th><th>数量</th><th>价格 / 金额</th><th>现金影响</th><th><span className="sr-only">操作</span></th></tr></thead><tbody>{trades.data?.items.map(item => <tr key={item.id}><td>{dateText(item.tradedOn)}</td><td><strong>{item.security.name}</strong><small>{item.security.tsCode}</small></td><td><StatusTag tone={item.type === 'SELL' || item.type === 'DIVIDEND' ? 'success' : 'blue'}>{tradeLabel(item.type)}</StatusTag></td><td>{item.quantity || '—'}</td><td>{money(item.price)}</td><td className={Number(item.cashImpact) >= 0 ? 'positive' : 'negative'}>{money(item.cashImpact)}</td><td>{manager && <><button className="text-action" onClick={() => setTrade(edit(item))}>编辑</button><button className="text-action danger" onClick={() => setDeleteTrade(item.id)}>删除</button></>}</td></tr>)}</tbody></table></div></QueryState></DataPanel>}
    {tab === 'accounts' && <DataPanel title="投资账户" action={manager && <Button size="small" onClick={() => setAccountDraft({ name: '', brokerName: '', currency: 'CNY' })}>新建账户</Button>}><QueryState loading={accounts.isLoading} error={accounts.error} empty={!accounts.data?.items.length} emptyTitle="还没有投资账户"><div className="compact-grid">{accounts.data?.items.map(item => <article className="data-card" key={item.id}><span className="card-icon">投</span><div><h3>{item.name}</h3><p>{item.brokerName} · {item.currency}</p></div>{manager && <div className="card-actions"><button onClick={() => setAccountDraft({ id: item.id, name: item.name, brokerName: item.brokerName, currency: item.currency })}>编辑</button><button onClick={() => archiveAccount.mutate(item.id)}>归档</button></div>}</article>)}</div></QueryState></DataPanel>}
    {tab === 'quotes' && <DataPanel title="收盘行情" meta="仅日线行情，不代表盘中实时价格" action={manager && <Button size="small" loading={refresh.isPending} onClick={() => refresh.mutate()}>手动刷新</Button>}><FormError error={refresh.error} />{refresh.data && <div className="inline-result">刷新结果：{refresh.data.state} · {refresh.data.refreshed} 个证券{refresh.data.error ? ` · ${refresh.data.error}` : ''}</div>}<QueryState loading={quotes.isLoading} error={quotes.error} empty={!quotes.data?.length} emptyTitle="没有持仓行情"><div className="quote-grid">{quotes.data?.map(item => <article key={item.securityId}><header><div><h3>{item.name}</h3><p>{item.tsCode}</p></div><strong>{money(item.price)}</strong></header><PriceState source={item.source} stale={item.stale} tradeDate={item.tradeDate} error={item.error} />{manager && <button onClick={() => { setManualQuote(item); setManual({ price: item.price ?? '', effectiveOn: new Date().toISOString().slice(0,10), note: '' }); }}>设置手工价格</button>}</article>)}</div></QueryState></DataPanel>}

    <Drawer open={trade !== null} title={trade?.id ? '编辑投资记录' : '记一笔投资'} description="持仓和收益将在保存后由服务器重新计算。" onClose={() => setTrade(null)}>{trade && <form className="feature-form" onSubmit={(e: FormEvent) => { e.preventDefault(); saveTrade.mutate(trade); }}><FormError error={saveTrade.error} /><label>投资账户<select required value={trade.accountId} onChange={e => setTrade({ ...trade, accountId: e.target.value })}><option value="">请选择</option>{accounts.data?.items.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>证券搜索<input value={securityQuery} onChange={e => setSecurityQuery(e.target.value)} placeholder="代码或名称" /></label><label>证券<select required value={trade.securityId} onChange={e => setTrade({ ...trade, securityId: e.target.value })}><option value="">请选择证券</option>{securities.data?.items.map(item => <option key={item.id} value={item.id}>{item.tsCode} · {item.name}</option>)}</select></label><label>业务类型<select value={trade.type} onChange={e => setTrade({ ...trade, type: e.target.value as InvestmentTradeType, quantity: ['BUY','SELL'].includes(e.target.value) ? trade.quantity : '', fee: ['BUY','SELL'].includes(e.target.value) ? trade.fee : '' })}>{(['BUY','SELL','DIVIDEND','FEE'] as InvestmentTradeType[]).map(value => <option key={value} value={value}>{tradeLabel(value)}</option>)}</select></label>{(trade.type === 'BUY' || trade.type === 'SELL') && <label>数量<input required inputMode="decimal" value={trade.quantity} onChange={e => setTrade({ ...trade, quantity: e.target.value })} /></label>}<label>{trade.type === 'BUY' || trade.type === 'SELL' ? '成交单价' : trade.type === 'DIVIDEND' ? '分红金额' : '费用金额'}<input required inputMode="decimal" value={trade.price} onChange={e => setTrade({ ...trade, price: e.target.value })} /></label>{(trade.type === 'BUY' || trade.type === 'SELL') && <label>附加费用<input inputMode="decimal" value={trade.fee} onChange={e => setTrade({ ...trade, fee: e.target.value })} /></label>}<label>日期<input type="date" value={trade.tradedOn} onChange={e => setTrade({ ...trade, tradedOn: e.target.value })} /></label><Button htmlType="submit" theme="solid" type="primary" loading={saveTrade.isPending}>保存投资记录</Button></form>}</Drawer>
    <Drawer open={accountDraft !== null} title={accountDraft?.id ? '编辑投资账户' : '新建投资账户'} onClose={() => setAccountDraft(null)}>{accountDraft && <form className="feature-form" onSubmit={e => { e.preventDefault(); saveAccount.mutate(accountDraft); }}><FormError error={saveAccount.error} /><label>账户名称<input required value={accountDraft.name} onChange={e => setAccountDraft({ ...accountDraft, name: e.target.value })} /></label><label>券商名称<input required value={accountDraft.brokerName} onChange={e => setAccountDraft({ ...accountDraft, brokerName: e.target.value })} /></label><label>币种<input value={accountDraft.currency} readOnly /></label><Button htmlType="submit" theme="solid" type="primary">保存账户</Button></form>}</Drawer>
    <Drawer open={manualQuote !== null} title={`手工价格 · ${manualQuote?.name ?? ''}`} description="手工价格会明确标记来源，不会伪装成外部行情。" onClose={() => setManualQuote(null)}>{manualQuote && <form className="feature-form" onSubmit={e => { e.preventDefault(); setManualPrice.mutate(); }}><FormError error={setManualPrice.error} /><label>价格<input required inputMode="decimal" value={manual.price} onChange={e => setManual({ ...manual, price: e.target.value })} /></label><label>生效日期<input required type="date" value={manual.effectiveOn} onChange={e => setManual({ ...manual, effectiveOn: e.target.value })} /></label><label>说明<textarea value={manual.note} onChange={e => setManual({ ...manual, note: e.target.value })} /></label><Button htmlType="submit" theme="solid" type="primary" loading={setManualPrice.isPending}>保存手工价格</Button></form>}</Drawer>
    <ConfirmDialog open={deleteTrade !== null} title="删除这笔投资记录？" detail="持仓、成本与收益会由服务器按剩余交易历史重新计算。" danger confirmLabel="删除记录" onClose={() => setDeleteTrade(null)} onConfirm={() => deleteTrade !== null && removeTrade.mutate(deleteTrade)} />
  </PageScaffold>;
}

function PriceState({ source, stale, tradeDate, error }: { source: 'TUSHARE' | 'MANUAL' | null; stale: boolean; tradeDate: string | null; error: string | null }) {
  if (error || !source) return <div className="price-state" aria-label="缺少行情"><StatusTag tone="danger">缺少价格</StatusTag><small>{error ?? '尚无可用价格'}</small></div>;
  return <div className="price-state" aria-label={`${source === 'MANUAL' ? '手工价格' : 'Tushare 日线'}，${stale ? '行情已过期' : '行情有效'}`}><StatusTag tone={stale ? 'warning' : 'success'}>{source === 'MANUAL' ? '手工价格' : 'Tushare 日线'}</StatusTag>{stale && <StatusTag tone="warning">行情已过期</StatusTag>}<small>{dateText(tradeDate)}</small></div>;
}
