package com.familyfinance.migration;

import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

final class StageOneDatabaseFixture {

    private StageOneDatabaseFixture() {
    }

    static Path create(Path database) {
        return create(database, false);
    }

    static Path createWithAdditionalUser(Path database) {
        return create(database, true);
    }

    private static Path create(Path database, boolean includeAdditionalUser) {
        try (Connection connection = DriverManager.getConnection(MigrationTestSupport.h2Url(database), "sa", "");
                Statement statement = connection.createStatement()) {
            createSchema(statement);
            insertDemoLedger(statement);
            if (includeAdditionalUser) {
                statement.execute("insert into app_users (id, household_id, username, password_hash, created_at) values (2, 1, 'legacy', 'encoded-password', timestamp with time zone '2026-09-01 00:00:00+00')");
            }
            return database;
        } catch (SQLException exception) {
            throw new IllegalStateException("Could not create Stage 1 H2 database fixture", exception);
        }
    }

    private static void createSchema(Statement statement) throws SQLException {
        statement.execute("create table households (id bigint generated by default as identity primary key, name varchar(255) not null, created_at timestamp with time zone not null)");
        statement.execute("create table app_users (id bigint generated by default as identity primary key, household_id bigint not null, username varchar(255) not null unique, password_hash varchar(255) not null, created_at timestamp with time zone not null, constraint fk_app_users_household foreign key (household_id) references households(id))");
        statement.execute("create table family_members (id bigint generated by default as identity primary key, household_id bigint not null, name varchar(255) not null, role_label varchar(255) not null, created_at timestamp with time zone not null, constraint fk_family_members_household foreign key (household_id) references households(id))");
        statement.execute("create table categories (id bigint generated by default as identity primary key, household_id bigint not null, kind varchar(255) not null, name varchar(255) not null, color varchar(255) not null, is_default boolean not null, created_at timestamp with time zone not null, constraint uk_categories_household_kind_name unique (household_id, kind, name), constraint fk_categories_household foreign key (household_id) references households(id))");
        statement.execute("create table financial_transactions (id bigint generated by default as identity primary key, household_id bigint not null, member_id bigint not null, category_id bigint not null, kind varchar(255) not null, amount_cents bigint not null, occurred_on date not null, merchant varchar(255), location varchar(255), note varchar(500), created_at timestamp with time zone not null, updated_at timestamp with time zone not null, constraint fk_transactions_household foreign key (household_id) references households(id), constraint fk_transactions_member foreign key (member_id) references family_members(id), constraint fk_transactions_category foreign key (category_id) references categories(id))");
        statement.execute("create index ix_financial_transactions_household_occurred_on on financial_transactions (household_id, occurred_on)");
    }

    private static void insertDemoLedger(Statement statement) throws SQLException {
        statement.execute("insert into households (id, name, created_at) values (1, '演示家庭', timestamp with time zone '2026-09-01 00:00:00+00')");
        statement.execute("insert into app_users (id, household_id, username, password_hash, created_at) values (1, 1, 'demo', 'encoded-password', timestamp with time zone '2026-09-01 00:00:00+00')");
        statement.execute("insert into family_members (id, household_id, name, role_label, created_at) values (1, 1, 'Kevin', '爸爸', timestamp with time zone '2026-09-01 00:00:00+00')");
        statement.execute("insert into categories (id, household_id, kind, name, color, is_default, created_at) values (1, 1, 'EXPENSE', '餐饮', '#D8664B', true, timestamp with time zone '2026-09-01 00:00:00+00')");
        for (int number = 1; number <= 12; number++) {
            statement.execute("insert into financial_transactions (household_id, member_id, category_id, kind, amount_cents, occurred_on, created_at, updated_at) values (1, 1, 1, 'EXPENSE', "
                    + number + ", date '2026-09-01', timestamp with time zone '2026-09-01 00:00:00+00', timestamp with time zone '2026-09-01 00:00:00+00')");
        }
    }
}
