import { useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import Button from '@douyinfe/semi-ui/lib/es/button';
import type { Budget, BudgetRevision, BudgetScopeType, BudgetUsage, Category, HouseholdRole, Member } from '../../api/contracts';
import { localYearMonth } from '../../shared/runtime';
import { DataPanel, Drawer, FormError, PageScaffold, QueryState, StatusTag, isManager, money, type RequestFn } from '../common';

type BudgetDraft = { id?: number; periodMonth: string; scopeType: BudgetScopeType; categoryId: number | null; memberId: number | null; amount: string; version: number; active: boolean };

export function BudgetsPage({ request, role }: { request: RequestFn; role: HouseholdRole }) {
  const queryClient = useQueryClient();
  const [month, setMonth] = useState(localYearMonth());
  const [draft, setDraft] = useState<BudgetDraft | null>(null);
  const [historyId, setHistoryId] = useState<number | null>(null);
  const usage = useQuery({ queryKey: ['budget-usage', month], queryFn: () => request<BudgetUsage[]>(`/api/budgets/usage?periodMonth=${month}&rollupCategories=true&includeInactive=true&page=0&size=50`) });
  const categories = useQuery({ queryKey: ['categories'], queryFn: () => request<Category[]>('/api/categories?projection=flat&page=0&size=100') });
  const members = useQuery({ queryKey: ['members'], queryFn: () => request<Member[]>('/api/members') });
  const revisions = useQuery({ queryKey: ['budget-revisions', historyId], queryFn: () => request<BudgetRevision[]>(`/api/budgets/${historyId}/revisions?page=0&size=50`), enabled: historyId !== null });
  const save = useMutation({ mutationFn: (value: NonNullable<typeof draft>) => request<Budget>(value.id ? `/api/budgets/${value.id}` : '/api/budgets', { method: value.id ? 'PATCH' : 'POST', body: value }), onSuccess: async () => { setDraft(null); await Promise.all([queryClient.invalidateQueries({ queryKey: ['budget-usage'] }), queryClient.invalidateQueries({ queryKey: ['dashboard'] }), queryClient.invalidateQueries({ queryKey: ['net-worth'] })]); } });
  const manager = isManager(role);
  const categoryName = (id: number | null) => categories.data?.find(item => item.id === id)?.name ?? '全部分类';
  const memberName = (id: number | null) => members.data?.find(item => item.id === id)?.name ?? '全家';
  const scopeName = (budget: Budget) => budget.scopeType === 'TOTAL' ? '家庭总预算' : budget.scopeType === 'CATEGORY' ? categoryName(budget.categoryId) : memberName(budget.memberId);
  return <PageScaffold title="预算管理" description="额度、已用和剩余均由服务器按已确认支出汇总。" primaryAction={manager ? { label: '新建预算', onClick: () => setDraft({ periodMonth: month, scopeType: 'TOTAL', categoryId: null, memberId: null, amount: '', version: 0, active: true }) } : undefined} readonly={!manager}>
    <div className="toolbar"><label>预算月份<input type="month" value={month} onChange={e => setMonth(e.target.value)} /></label><StatusTag tone="blue">分类预算包含子分类</StatusTag></div>
    <QueryState loading={usage.isLoading} error={usage.error} empty={!usage.data?.length} emptyTitle="这个月还没有预算" emptyDetail={manager ? '新建家庭总预算、分类预算或成员预算。' : '家庭管理员还没有设置本月预算。'}>
      <div className="budget-grid">{usage.data?.map(item => { const percent = Math.max(0, Math.min(100, Number(item.percent))); const tone = !item.budget.active ? 'neutral' : item.status === 'OVER_BUDGET' ? 'danger' : item.status === 'NEAR_LIMIT' || item.status === 'AT_LIMIT' ? 'warning' : 'success'; return <article className="budget-card" key={item.budget.id}><header><div><span>{item.budget.periodMonth}</span><h2>{scopeName(item.budget)}</h2></div><StatusTag tone={tone}>{!item.budget.active ? '已停用' : item.status === 'OVER_BUDGET' ? '已超支' : item.status === 'NEAR_LIMIT' ? '接近额度' : item.status === 'AT_LIMIT' ? '已用完' : '进度正常'}</StatusTag></header><div className="budget-values"><strong>{money(item.spent)}</strong><span> / {money(item.budget.amount)}</span></div><div className="progress-track" aria-label={`预算使用 ${item.percent}%`}><i style={{ width: `${percent}%` }} className={tone} /></div><footer><span>剩余 {money(item.remaining)}</span><span>{item.percent}%</span></footer>{manager && <div className="inline-actions"><button onClick={() => setDraft(item.budget)}>调整预算</button><button onClick={() => setHistoryId(item.budget.id)}>修订记录</button></div>}</article>; })}</div>
    </QueryState>
    <Drawer open={draft !== null} title={draft && 'id' in draft && draft.id ? '调整预算' : '新建预算'} description="每次调整都会保留不可变修订记录。" onClose={() => setDraft(null)}>{draft && <form className="feature-form" onSubmit={(e: FormEvent) => { e.preventDefault(); save.mutate(draft); }}><FormError error={save.error} /><label>月份<input type="month" value={draft.periodMonth} onChange={e => setDraft({ ...draft, periodMonth: e.target.value })} required /></label><label>预算范围<select value={draft.scopeType} onChange={e => setDraft({ ...draft, scopeType: e.target.value as BudgetScopeType, categoryId: null, memberId: null })}><option value="TOTAL">家庭总预算</option><option value="CATEGORY">支出分类</option><option value="MEMBER">家庭成员</option></select></label>{draft.scopeType === 'CATEGORY' && <label>支出分类<select required value={draft.categoryId ?? ''} onChange={e => setDraft({ ...draft, categoryId: Number(e.target.value) })}><option value="">请选择</option>{categories.data?.filter(item => item.kind === 'expense').map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}{draft.scopeType === 'MEMBER' && <label>成员<select required value={draft.memberId ?? ''} onChange={e => setDraft({ ...draft, memberId: Number(e.target.value) })}><option value="">请选择</option>{members.data?.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}<label>预算金额<input inputMode="decimal" required value={draft.amount} onChange={e => setDraft({ ...draft, amount: e.target.value })} /></label>{'id' in draft && draft.id && <label className="switch-line"><input type="checkbox" checked={draft.active} onChange={e => setDraft({ ...draft, active: e.target.checked })} />启用该预算</label>}<Button htmlType="submit" theme="solid" type="primary" loading={save.isPending}>保存预算</Button></form>}</Drawer>
    <Drawer open={historyId !== null} title="预算修订记录" onClose={() => setHistoryId(null)}><QueryState loading={revisions.isLoading} error={revisions.error} empty={!revisions.data?.length} emptyTitle="还没有修订"><ol className="timeline-list">{revisions.data?.map(item => <li key={item.id}><i /><div><strong>{money(item.oldAmount)} → {money(item.newAmount)}</strong><p>{new Date(item.changedAt).toLocaleString('zh-CN')}</p></div></li>)}</ol></QueryState></Drawer>
  </PageScaffold>;
}
