package com.familyfinance.loan;
import com.familyfinance.accounting.*;
import com.familyfinance.shared.ApiEnvelope; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import java.util.List;
@RestController @RequestMapping("/api/loans") public class LoanController { private final LoanPayoffService payoff; private final LoanService loans; private final LoanPrepaymentService prepayments; private final AccountingCommandExecutor executor; private final LoanRepaymentService repayments; private final LoanDebtOverviewService overview; LoanController(LoanService loans,LoanPrepaymentService prepayments,AccountingCommandExecutor executor,LoanPayoffService payoff,LoanRepaymentService repayments,LoanDebtOverviewService overview){this.payoff=payoff;this.loans=loans;this.prepayments=prepayments;this.executor=executor;this.repayments=repayments;this.overview=overview;}
 @GetMapping("/debt-overview") ApiEnvelope<LoanDebtOverviewResponse> debtOverview(Authentication a){return ApiEnvelope.data(overview.overview(a));}
 @GetMapping ResponseEntity<ApiEnvelope<LoanPage>> list(Authentication a,@RequestParam(defaultValue="ACTIVE") LoanStatus status,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="20") int size){LoanPage p=loans.list(a,status,page,size);return ResponseEntity.ok().header("X-Page",String.valueOf(p.page())).header("X-Page-Size",String.valueOf(p.size())).header("X-Has-Next",String.valueOf(p.hasNext())).body(ApiEnvelope.data(p));}
 @GetMapping("/{id}") ApiEnvelope<LoanResponse> get(Authentication a,@PathVariable long id){return ApiEnvelope.data(loans.get(a,id));}
 @GetMapping("/{id}/prepayments") ApiEnvelope<List<LoanPrepaymentResponse>> history(Authentication a,@PathVariable long id){return ApiEnvelope.data(loans.prepaymentHistory(a,id));}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) ApiEnvelope<LoanResponse> create(Authentication a,@RequestBody LoanCreateRequest r,@RequestHeader(value="Idempotency-Key",required=false) String supplied){String key=AccountingRequests.key(supplied);return ApiEnvelope.data(executor.execute(()->loans.create(a,r,key)));}
 @PatchMapping("/{id}") ApiEnvelope<LoanResponse> update(Authentication a,@PathVariable long id,@RequestBody LoanPatchRequest r,@RequestHeader(value="Idempotency-Key",required=false) String supplied){String key=AccountingRequests.key(supplied);return ApiEnvelope.data(executor.execute(()->loans.update(a,id,r,key)));}
 @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void archive(Authentication a,@PathVariable long id,@RequestHeader(value="Idempotency-Key",required=false) String supplied){String key=AccountingRequests.key(supplied);executor.execute(()->{loans.archive(a,id,key);return null;});}
 @PostMapping("/{id}/cancel") @ResponseStatus(HttpStatus.NO_CONTENT) void cancel(Authentication a,@PathVariable long id,@RequestHeader(value="Idempotency-Key",required=false) String supplied){String key=AccountingRequests.key(supplied);executor.execute(()->{loans.cancel(a,id,key);return null;});}
 @GetMapping("/{id}/schedule") ResponseEntity<ApiEnvelope<List<LoanInstallmentResponse>>> schedule(Authentication a,@PathVariable long id,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="50") int size,@RequestParam(defaultValue="ALL") LoanScheduleView view){LoanSchedulePage p=loans.schedule(a,id,page,size,view);return ResponseEntity.ok().header("X-Page",String.valueOf(p.page())).header("X-Page-Size",String.valueOf(p.size())).header("X-Total-Elements",String.valueOf(p.totalElements())).header("X-Total-Pages",String.valueOf(p.totalPages())).header("X-Has-Next",String.valueOf(p.hasNext())).body(ApiEnvelope.data(p.items()));}
 @GetMapping("/{id}/payoff-quote") ApiEnvelope<LoanPayoffQuote> quote(Authentication a,@PathVariable long id,@RequestParam java.time.LocalDate paidOn,@RequestParam(required=false) Long paymentAccountId,@RequestParam(required=false) String interestAmount){return ApiEnvelope.data(payoff.quote(a,id,paidOn,paymentAccountId,interestAmount));}
 @GetMapping("/{id}/prepayment-preview") ApiEnvelope<LoanPrepaymentPreview> preview(Authentication a,@PathVariable long id,@RequestParam String amount,@RequestParam java.time.LocalDate paidOn,@RequestParam(required=false) PrepaymentStrategy strategy,@RequestParam(required=false) Long paymentAccountId){return ApiEnvelope.data(prepayments.preview(a,id,amount,paidOn,strategy,paymentAccountId));}
 @PostMapping("/{id}/payoff") ApiEnvelope<LoanPrepaymentResponse> payoff(Authentication a,@PathVariable long id,@RequestBody LoanPayoffRequest request){return ApiEnvelope.data(executor.execute(()->payoff.payoff(a,id,request)));}
 @PostMapping("/{id}/prepay") ApiEnvelope<LoanPrepaymentResponse> prepay(Authentication a,@PathVariable long id,@RequestBody LoanPrepaymentRequest r){return ApiEnvelope.data(executor.execute(()->prepayments.prepay(a,id,r)));}
 @GetMapping("/{id}/repayment-preview") ApiEnvelope<LoanRepaymentPreview> repaymentPreview(Authentication a,@PathVariable long id,@RequestParam String additionalPrincipal,@RequestParam java.time.LocalDate paidOn,@RequestParam(required=false) Long paymentAccountId,@RequestParam(required=false) PrepaymentStrategy strategy,@RequestParam(required=false) Integer targetPeriods){return ApiEnvelope.data(repayments.preview(a,id,additionalPrincipal,paidOn,paymentAccountId,strategy,targetPeriods));}
 @PostMapping("/{id}/repayment") ApiEnvelope<LoanRepaymentResponse> repay(Authentication a,@PathVariable long id,@RequestBody LoanRepaymentRequest r){return ApiEnvelope.data(executor.execute(()->repayments.repay(a,id,r)));}
 @GetMapping("/{id}/repayments") ApiEnvelope<List<LoanRepaymentResponse>> repayments(Authentication a,@PathVariable long id){return ApiEnvelope.data(repayments.history(a,id));}
}
