alter table financial_transactions drop constraint ck_financial_transactions_source;
alter table financial_transactions add constraint ck_financial_transactions_source_v12
    check ((source_type = 'MANUAL' and source_id is null)
        or (source_type in ('RECURRING', 'LOAN', 'LOAN_PAYMENT', 'LOAN_PREPAYMENT') and source_id is not null));

create sequence loan_prepayment_id_seq start with 1 increment by 1;
create table loan_prepayments (
    id bigint primary key,
    household_id bigint not null,
    loan_id bigint not null,
    request_key varchar(100) not null,
    amount_cents bigint not null,
    paid_on date not null,
    transaction_id bigint,
    created_at timestamp with time zone not null,
    constraint uk_loan_prepayments_request unique (household_id, loan_id, request_key),
    constraint uk_loan_prepayments_transaction unique (transaction_id),
    constraint ck_loan_prepayments_amount check (amount_cents > 0),
    constraint ck_loan_prepayments_request check (length(trim(request_key)) > 0),
    constraint fk_loan_prepayments_household foreign key (household_id) references households(id),
    constraint fk_loan_prepayments_loan_household foreign key (loan_id, household_id) references loans(id, household_id),
    constraint fk_loan_prepayments_transaction_household foreign key (transaction_id, household_id)
        references financial_transactions(id, household_id)
);
create index ix_loan_prepayments_household_loan on loan_prepayments (household_id, loan_id, id);

create table market_issues (
    id bigint generated by default as identity primary key,
    household_id bigint not null,
    error_code varchar(64) not null,
    active boolean not null,
    occurred_at timestamp with time zone not null,
    resolved_at timestamp with time zone,
    constraint uk_market_issues_household_code unique (household_id, error_code),
    constraint fk_market_issues_household foreign key (household_id) references households(id)
);
